name: vllm-local-rag
services:
  vllm:
    build:
      context: .
      dockerfile: Dockerfile.vllm
    container_name: vllm_server
    shm_size: "16gb"
    gpus: all
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
    ports:
      - "8001:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface

  fastapi:
    build: .
    container_name: rag-pdf-agent-vllm
    ports:
      - "8000:8000"
    environment:
      - VLLM_BASE_URL=http://vllm:8000/v1 
      - API_KEY=${API_KEY}
    volumes:
      - ./data:/app/data
      - ./db:/app/db
      - ~/.cache/huggingface:/root/.cache/huggingface
    depends_on:
      - vllm